version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - url-shortener-network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: url-shortener-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - url-shortener-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: url-shortener-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: url_shortener
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - url-shortener-network

  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - url-shortener-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: url-shortener-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    networks:
      - url-shortener-network
    depends_on:
      - mysql

volumes:
  mysql_data:
  redis_data:

networks:
  url-shortener-network:
    driver: bridge
